---
kind: pipeline
type: docker
name: demo

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: alpine
    commands:
      - echo test

  - name: build
    image: alpine
    commands:
      - echo build

  - name: publish
    image: alpine
    commands:
      - echo publish

trigger:
  event:
    - push
    - tag
---
# https://plugins.drone.io/plugins/email
kind: pipeline
type: docker
name: notify-test

steps:
  - name: notify
    image: drillster/drone-email
    settings:
      host: smtp.ym.163.com
      # port: 994
      username: admin@nbaxp.com
      password: aA123456!
      from: admin@nbaxp.com
depends_on:
  - demo
---
kind: pipeline
type: docker
name: aspnet

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: mcr.microsoft.com/dotnet/sdk:6.0
    commands:
      - cd aspnet
      - dotnet build
      - dotnet test

  - name: publish
    image: plugins/docker
    environment:
      PLUGIN_REGISTRY: hub.nbaxp.com
      PLUGIN_REPO: hub.nbaxp.com/demo/aspnet
    settings:
      dockerfile: Dockerfile.aspnet
      username: admin
      password: wanggang123!
      tags:
        - latest
        - ${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}-${DRONE_REPO_BRANCH}-${DRONE_COMMIT_SHA:0:8}

trigger:
  event:
    - push
    - tag
