version: "3.9"

services:
  # composer:
  #   image: composer:2.3
  #   ports:
  #     - 80:8000
  #   volumes:
  #     - ./php:/app
  #   command: tail -f /dev/null
  nginx:
    image: nginx:1.23.0
    restart: always
    container_name: nginx
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./php/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php:/usr/share/nginx/html
    depends_on:
      - php
  php:
    image: php:8.1-fpm-alpine
    ports:
      - 9000:9000
      - 9001:80
    volumes:
      - ./php:/var/www/html
