FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source

COPY aspnet .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine
WORKDIR /app
EXPOSE 80
COPY --from=build /app .
ENTRYPOINT ["dotnet", "aspnet.dll"]
